####  LOGGING   ####
logging.pattern.console=${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}
logging.level.org.springframework.boot.autoconfigure.security=DEBUG
logging.level.org.springframework.boot.context.properties=TRACE
####  SECURITY LOGS  ####
logging.level.org.springframework.security=${SPRING_SECURITY_LOG_LEVEL:TRACE}
####  SQL LOGS  ####
spring.jpa.show-sql=${JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=${HIBERNATE_FORMAT_SQL:false}

#### RSA KEYS ####
jwt.rsa.private-key=classpath:keys/private_key.pem
jwt.rsa.public-key=classpath:keys/public_key.pem

#### TTL ####
token.ttl.pkce-access=10m
token.ttl.pkce-refresh=30m
token.ttl.client-credentials-access=10m

### ADMIN CREDENTIALS ###
admin.email=admin@mobilityapp.com
admin.password=p##s$worDd
admin.phone=00000000

#### JWT SIGNING SECRET ####
jwt.signing.secret.key=dGhpcyBpcyBhIGRldmVsb3BtZW50IHNlY3JldCBrZXkgMzI=

#### API SECRET ####
oauth2.client.mobility-api.secret=thes333crEt

#### LOGIN PAGE ####
oauth2.redirect.uri=http://localhost:9999/login/callback
oauth2.redirect.logout.uri=http://localhost:9999/login/callback

#### URL ####
issuer.url=http://localhost:9000/auth-server
cors.allowed-origins=http://localhost:9999

#### RABBITMQ ####
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=mobilityqueueuser
spring.rabbitmq.password=Strong-password1

#### COOKIES ####
csrf.cookie.secure=false
csrf.cookie.same-site=Lax